services:
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=qp_grocery_app
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
